In [1]:
import numpy as np
a = np.random.randn(5)

In [2]:
print(a)

[-0.46835492 -0.73854182 -0.45724808  0.18392131 -0.3253945 ]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.46835492 -0.73854182 -0.45724808  0.18392131 -0.3253945 ]


In [5]:
print(np.dot(a,a.T))

1.1135847907838436


In [6]:
a = np.random.randn(5,1)

In [7]:
print(a)

[[ 0.1359514 ]
 [-1.72539022]
 [-1.74960231]
 [-0.56211102]
 [-0.54464067]]


In [8]:
print(a.T)

[[ 0.1359514  -1.72539022 -1.74960231 -0.56211102 -0.54464067]]


这是一个笔记

In [9]:
print(np.dot(a,a.T))

[[ 0.01848278 -0.23456921 -0.23786088 -0.07641978 -0.07404466]
 [-0.23456921  2.97697139  3.01874671  0.96986085  0.93971769]
 [-0.23786088  3.01874671  3.06110826  0.98347074  0.95290459]
 [-0.07641978  0.96986085  0.98347074  0.3159688   0.30614852]
 [-0.07404466  0.93971769  0.95290459  0.30614852  0.29663346]]
